### ISSUE TITLE
The RawGit CDN is going to be closing/shutting down soon

### ISSUE THREAD

**Issue by abbasldn** [akabab/superhero-api#3]
So what will happen to your API?

**Comment by JideGuru** [comment]
The base URL can still be used.
https://akabab.github.io/superhero-api/api

**Comment by kigiri** [comment]
You can also use githack url: [rawcdn.githack.com/akabab/superhero-api/0.2.0/api/all.json](https://rawcdn.githack.com/akabab/superhero-api/0.2.0/api/all.json)

To use without traffic limits or throttling.

See https://raw.githack.com/

**Comment by akabab** [comment]
fixed in v0.3.0 252c436
